# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Contest start time')),
                ('end_time', models.DateTimeField(verbose_name='Contest end time')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('problem_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Submission time')),
                ('submission_id', models.IntegerField()),
                ('verdict', models.IntegerField()),
                ('lang', models.CharField(max_length=15)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_contest.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_contest.User'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='virtual_contest.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(to='virtual_contest.User'),
        ),
    ]
